name: Run Script on AWS Ubuntu Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Execute remote SSH commands to run script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/woc-blog
          ./update.sh
